### ISSUE TITLE
Could you add a multitarget mode?

### ISSUE THREAD

**Issue by imfht** [r0oth3x49/Xpath#1]
Hi, I'm  fiht form China.
I have spend a lot of time in how to find injection point automatic.
And the following words is to show you what I have done. Maybe a little stupid but I can not find a better way to achieve this.
1. use a seed url.
2. spider download the url and parse the page to find more url(to crawl) and save the url that may have inject point.(such as http://www.example.com/search?id=1).
3. use sqlmap api to test this urls.

Does you have more advice to the model?
And could add a multi target mode to Xpath?
Thanks a lot, noting can I do but a star.

**Comment by r0oth3x49** [comment]
Thank you for your appreciation,  I will consider your suggestions in next version of xpath.
**about your model**
what else you want in that model i think if your purpose is to inject the site then this model is good enough but if you want further then this can be extended.
