### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'errors'

### ISSUE THREAD

**Issue by merlinwoff** [r0oth3x49/Xpath#3]
Hi,
I am testing some xPath Injection Tools at the moment, and tried to run the xpath.py script.
The following output was produced:

` _    _        ___ 
\  \/  /___   __H__ _    {3.0#stable}
 \    /| . |___[']_| |_
 /    \|  _| .'["]_|   |
/_ /\ _|_| |__,[)] |_|_| 
                v..      https://github.com/r0oth3x49/Xpath

[!] Legal disclaimer: Usage of xpath for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developer assume no liability and is not responsible for any misuse or damage caused by this program.

Traceback (most recent call last):
  File "xpath.py", line 326, in <module>
    main()
  File "xpath.py", line 276, in main
    force_ssl=args.force_ssl,
  File "/opt/Xpath/xpath/xpath.py", line 73, in perform_injection
    set_level(verbose_level, filepath)
  File "/opt/Xpath/xpath/logger/colored_logger.py", line 191, in set_level
    filepath, mode="a", encoding="utf-8", errors="ignore"
TypeError: __init__() got an unexpected keyword argument 'errors'
`

I am running Python 3.6.8 and installed all requirements using pip.

Does anyone have a clue, what am I doing wrong?

Thank you very much for your work!

**Comment by r0oth3x49** [comment]
hi @merlinwoff thanks for appreciation and using Xpath. actually i have tested it with python 3.9 i will check with older version and let you know if any fix is required will push it ASAP.

**Comment by merlinwoff** [comment]
Thank you very much for your help in advance!

**Comment by r0oth3x49** [comment]
@merlinwoff i have just pushed a fix, try it should work fine now. I 'm going to close the issue now, Reopen the issue if you see the error occurs again.
